[[redirects]]
  from = "/blogs"
  to = "https://what-is-an-agent.netlify.app/blogs"
  status = 200
  force = true

[[redirects]]
  from = "/blogs/*"
  to = "https://what-is-an-agent.netlify.app/blogs/:splat"
  status = 200
  force = true
